services:
  mysql:
    image: mysql:8.4.7

    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

    ports:
      - "3307:3306"